### ISSUE TITLE
Support CustomModelData

### ISSUE THREAD

**Issue by 2173204318** [BentoBoxWorld/ControlPanel#21]
### Is your feature request related to a problem?

Support CustomModelData

### Describe the solution you'd like.

Support CustomModelData

### Describe alternatives you've considered.

Support CustomModelData

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by tastybento** [comment]
What do you want it to do? Explain more.

**Comment by CamperSamu** [comment]
By supporting CustomModelData, it meant using different models for the items via the CustomModelData NBT Tag.
CustomModelData can be used to add custom UI elements to Minecraft UIs.
@tastybento I suggest to reopen this issue and implement it since it would be very beneficial to the plugin.

Here some example from the Nova plugin and SlimeFun plugin (using the unofficial resource pack for SlimeFun):
![image](https://user-images.githubusercontent.com/32773961/207895317-d840cd4c-9524-47e0-a503-8efadaae459f.png)
![image](https://user-images.githubusercontent.com/32773961/207895354-7cc0c6b8-fd1a-4d0d-b081-5ac5de726a1b.png)
![image](https://user-images.githubusercontent.com/32773961/207895367-e3df4171-44c8-40fd-ad8d-bd70c7aecacb.png)
![image](https://user-images.githubusercontent.com/32773961/207895420-ea5622fa-a40b-4c88-952c-59a89dee128f.png)
![image](https://user-images.githubusercontent.com/32773961/207895477-00cf40c4-c319-4379-b8d7-16890a7ae9c1.png)

**Comment by BONNe** [comment]
Creating a proper request would be more beneficial,  then just one word spamming all ower. This will not be opened.

**Comment by CamperSamu** [comment]
I'll make a more detailed issue then!
